[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.3"
futures = "0.3.25"
rand = "0.7.3"
tokio = { version = "1.23.0", features = ["full"] }
